baseURL = 'https://0xtard.github.io/'
languageCode = 'en-us'
title = '0xtard your friendly hacker'
theme="hugo-theme-terminal"

[params]
	# config help: https://github.com/panr/hugo-theme-terminal?tab=readme-ov-file#how-to-configure
	# center theme with default width
	centerTheme = true